### ISSUE TITLE
 One bug.

### ISSUE THREAD

**Issue by mat-shur** [Y-Less/sscanf#26]
There is, for example, an array:
`new str[16] = "abc,dfg,hjk,lmn"`

From this line I want to pull "dfg":
`new coun[10];
sscanf(str, "p<,>{s[10]}s[10]", coun);` - Logically, this should work, but it displays: "dfg,hjk,lmn", until you put a space at the end (it fixes this bug, for some reason) - 
`sscanf(str, "p<,>{s[10]}s[10] ", coun);`

**Comment by Crayder** [comment]
I think we just need a way to disable the space still being used as a separator. Currently with the way you did it both ` ` and `,` are separators which is what I'm [totally assuming] thinking this bug is caused by. If there was an alternative `p` operator (perhaps simply `p!` or something) that would make ONLY the characters included separators and NOT the space character I think this would be solved. This would be fantastic for many cases where I've come across similar issues.

EDIT: per [this line](https://github.com/maddinat0r/sscanf/blob/90c81c35dadcfce84ba6ada85ccb5a56f6ea8819/utils.cpp#L184) the space character is always included, with custom delimiters or not.

**Comment by mat-shur** [comment]
I'm sorry, but I didn't understand a bit, ` ` - is the best solution to this problem at the moment?

**Comment by Crayder** [comment]
Ah no, I'm wrong by miles, I tested my theory (which wasn't as simple as I initially thought, and broke other things).

However I think what you found may be useful for things. I absolutely never would've found that simply adding a space to the format resolves just the next small string. I've just been used to assuming the string specifier just takes the rest of the string and this is even how it's explained in the docs.

I think we should keep it how it is and just document the fact that adding a space makes the string specifier actually stop!

**Comment by mat-shur** [comment]
Thanks for the info and good answers, it was nice to chat.

P.S.: Hope to see a new fad in the documentation. :)

**Comment by Y-Less** [comment]
I'm not sure if this was documented at the time, but this isn't a bug.  Adding a space changing the behaviour of `s` is actually intended and (now) documented.
