### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by Dmitriy51** [Y-Less/sscanf#35]
f(sscanf(params, "d", player)) return SendClientMessagef(playerid, red,"|USE|: {333333} /ban |id]");
if(!SSCANF_IsConnected(player)) return SendClientMessagef(playerid, red,"|ERROR|: {00FFFF}Player not connected!");

SSCANF_IsConnected(player) this function crash the server, if (player = -11111111111 or player = 11111111111  )

**Comment by IstuntmanI** [comment]
You have to use the "u" specifier instead of the "d" one. Then, instead of checking for `!SSCANF_IsConnected(player)`, you can simply use `player == INVALID_PLAYER_ID`. "u" automatically checks for invalid names/IDs in the input and puts `INVALID_PLAYER_ID` in the required parameter.

If you really want to keep the "d" specifier, so a player name won't be able to be used, the check should probably look like
```pawn
if(!(0 <= player < MAX_PLAYERS) || !SSCANF_IsConnected(player)) return SendClientMessagef(playerid, red,"|ERROR|: {00FFFF}Player not connected!");
```

**Comment by Dmitriy51** [comment]
> You have to use the "u" specifier instead of the "d" one. Then, instead of checking for `!SSCANF_IsConnected(player)`, you can simply use `player == INVALID_PLAYER_ID`. "u" automatically checks for invalid names/IDs in the input and puts `INVALID_PLAYER_ID` in the required parameter.
> 
> If you really want to keep the "d" specifier, so a player name won't be able to be used, the check should probably look like
> 
> ```pawn
> if(!(0 <= player < MAX_PLAYERS) || !SSCANF_IsConnected(player)) return SendClientMessagef(playerid, red,"|ERROR|: {00FFFF}Player not connected!");
> ```

thaks

**Comment by Y-Less** [comment]
Why are you calling `SSCANF_IsConnected` anyway?  That's an internal function.

**Comment by Y-Less** [comment]
I've now hidden this function completely.
