### ISSUE TITLE
Mistake in condition?

### ISSUE THREAD

**Issue by milous22** [Y-Less/sscanf#9]
How does the code work on rows 339, 343, 399, 403 in _sscanf.inc_? Probably there are mistakes.

**Comment by IstuntmanI** [comment]
Those lines are fine: http://wiki.sa-mp.com/wiki/Strval.

This line:
```pawn
if ('0' <= string[0] <= '9')
```
checks if the first character of the passed string is a number between 0 and 9, so it does a minor check whether the string has a bigger probability to be an actual number. So a string of "9432" continues in the next block, as well as "0433", "425", but not "+425", "-425", "sdfjdsa", "STRING".
Inside that ```if```, ```ret``` is created with the value of the string converted to a number, if possible. Then another check is made, to check if the converted number is between those valid intervals, if it is, then that number is correct and it is returned. The kustom specifier fills a passed variable with the ID, which is correct.

The only problem in that code is with the weapons check, because ```strlen``` returns ```0``` if the passed string is not a number (string examples: "45as", "9asd", everything starting with a number between 0 and 9), so an invalid non-numeric string may actually fill the variable with ```0``` in that block of code, which is the "```Unarmed```" weapon ID, which isn't correct.

**Comment by milous22** [comment]
I mean the format of these conditions, because:
```
printf("%i", (0 <= -1 <= 2)); // printed: "0"
printf("%i", (0 <= 0 <= 2)); // printed: "0"
printf("%i", (0 <= 1 <= 2)); // printed: "0"
printf("%i", (0 <= 2 <= 2)); // printed: "0"
printf("%i", (0 <= 3 <= 2)); // printed: "0"
```
Expression "a < b < c" is compiled as "(a < b) < c", not "a < b && b < c".

**Comment by IstuntmanI** [comment]
Well, in C it is compiled as "( a < b ) < c", while in Pawn is compiled as "a < b && b < c". Did you test that ?

```pawn
printf("%d", (0 <= -1 <= 2)); // should print: "0"
printf("%d", (0 <= 0 <= 2)); // should print: "1"
printf("%d", (0 <= 1 <= 2)); // should print: "1"
printf("%d", (0 <= 2 <= 2)); // should print: "1"
printf("%d", (0 <= 3 <= 2)); // should print: "0"
```

EDIT: I tested it with a newer compiler: https://www.tutorialspoint.com/compile_pawn_online.php and it is exactly like on SA-MP's Pawn, just like my expected results.

**Comment by milous22** [comment]
I tested with original compiler (Win Server package from sa-mp.com).
[http://i.imgur.com/tL6b8H2.png/](http://i.imgur.com/tL6b8H2.png/)

**Comment by IstuntmanI** [comment]
That's weird. I tested that code with the original SA-MP Pawn compiler and it indeed prints 0, 0, 0, 0, 0. But here's another test:
![screenshot_3](https://user-images.githubusercontent.com/6208948/29138087-32f5e4a0-7d4b-11e7-8a40-74f88b5f702d.png)

I didn't know that range checks are different for rvalues and lvalues.

So the code from sscanf is still correct, as it uses an lvalue.

It is probably something that Pawn didn't implement until a newer version (that's probably why the online compiler worked fine, it is a newer version), probably because there's usually no need to manually check ranges of simple rvalues just like that and they probably missed that.
